apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ubuntu"
  template:
    metadata:
      labels:
        app: "ubuntu"
    spec:
      serviceAccountName: k8s-101-role
      containers:
        - name: ubuntu
          image: knoxuser/kubectl
          command:
            - sleep
            - infinity
