apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ubuntu
  name: ubuntu-dirtypipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-dirtypipe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ubuntu-dirtypipe
    spec:
      containers:
        - image: knoxuser/ubuntu20.04
          name: ubuntu-dirtypipe
          command: ["/bin/sleep", "3650d"]


